umbrella-reloader:
  reloader:
    deployment:
      resources:
        limits:
          memory: "256Mi"
        requests:
          cpu: "50m"
          memory: "256Mi"
      labels:
        environment: dev
